import { PickerLocale } from "antd/es/date-picker/generatePicker";

export const locale: PickerLocale = {
  lang: {
    locale: "es_ES",
    placeholder: "Selecciona una fecha",
    rangePlaceholder: ["Fecha inicial", "Fecha fin"],
    today: "Hoy",
    now: "Ahora",
    backToToday: "Ir a hoy",
    ok: "OK",
    clear: "Limpiar",
    month: "Mes",
    year: "Año",
    timeSelect: "Seleccionar hora",
    dateSelect: "Seleccionar fecha",
    monthSelect: "Selecciona un mes",
    yearSelect: "Selecciona un año",
    decadeSelect: "Selecciona una decada",
    yearFormat: "YYYY",
    dateFormat: "M/D/YYYY",
    dayFormat: "D",
    dateTimeFormat: "M/D/YYYY HH:mm:ss",
    monthFormat: "MMMM",
    monthBeforeYear: true,
    previousMonth: "Anterior mes",
    nextMonth: "Próximo mes",
    previousYear: "Anterior ano",
    nextYear: "Próximo año",
    previousDecade: "Anterior decada",
    nextDecade: "Próxima decada",
    previousCentury: "Anterior siglo",
    nextCentury: "Próximo siglo",
    shortWeekDays: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
    shortMonths: [
      "Ene",
      "Feb",
      "Mar",
      "Abr",
      "May",
      "Jun",
      "Jul",
      "Ago",
      "Sep",
      "Oct",
      "Nov",
      "Dic",
    ],
  },
  timePickerLocale: {
    placeholder: "Seleccionar hora",
  },
  dateFormat: "YYYY-MM-DD",
  dateTimeFormat: "YYYY-MM-DD HH:mm:ss",
  weekFormat: "YYYY-wo",
  monthFormat: "YYYY-MM",
};
